# -*- coding: utf-8 -*-
"""Task_1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I27gkSWRV1Aj_PBLdBnl8XDcbIU7B9wU
"""

from functools import wraps
import time


def decor_1(func):
    @wraps(func)
    def inner(*args, **kwargs):
        start_time = time.perf_counter()
        result = func(*args, **kwargs)
        end_time = time.perf_counter()
        total_time = end_time - start_time
        print(
            f'Function {func.__name__}{args} {kwargs} executed in {total_time:.4f} seconds')
        return result
    return inner


@decor_1
def cal_st(num):
    """
    Simple function that returns sum of all numbers up to the square of num.
    """
    total = sum((x for x in range(0, num**2)))
    return total


if __name__ == '__main__':
    cal_st(10)
    cal_st(100)
    cal_st(1000)
    cal_st(5000)
    cal_st(10000)
